import { normalizeProfile } from "./sports.js";
import { ingestNationalRecordsIntoDb } from "./nationalRecordsPdfParser.js";

export async function seedOpportunities(db) {
  if ((await db.list("opportunities")).length) return;
  for (const [i, type] of [
    "Trial",
    "Scholarship",
    "Competition",
    "Academy",
    "Sponsorship",
    "Government scheme",
  ].entries())
    await db.put("opportunities", {
      id: "sample-" + i,
      ownerId: "system",
      sample: true,
      title: [
        "State sprint development trial",
        "Next generation athlete grant",
        "Open district athletics meet",
        "Grassroots training residency",
        "Equipment access fellowship",
        "Inclusive sport support programme",
      ][i],
      type,
      sport: i === 1 || i === 4 ? "All sports" : "Athletics",
      event: "",
      unit: "sec",
      minResult: 0,
      maxResult: 0,
      location: i % 2 ? "All India" : "Maharashtra",
      minAge: 14,
      maxAge: 25,
      deadline: "2027-06-30",
      classification: "",
      url: "",
      description:
        "Illustrative listing for demonstrating eligibility matching. This is not a live opportunity or an affiliation with any organisation.",
    });
}
export async function seedAthlete(db, id) {
  const date = (n) =>
    new Date(Date.now() - n * 86400000).toISOString().slice(0, 10);
  const profile = normalizeProfile({
    id,
    ownerId: id,
    name: "Aarav Sharma",
    sport: "Athletics",
    event: "100m",
    unit: "sec",
    state: "Maharashtra",
    district: "Nashik",
    birthDate: "2007-04-18",
    gender: "Male",
    classification: "Open",
    equipment: "Open ground, resistance band",
    target: 11.9,
    goal: "Break the 12-second barrier and qualify for state trials.",
    education: "Class 12",
    competitionDate: "",
    coachId: "",
    sharePerformance: false,
    shareHealth: false,
    allowAnalytics: false,
    sportProfile: {
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      measurement: {
        type: "time",
        unit: "sec",
        unitLabel: "seconds",
        direction: "lower_is_better",
      },
    },
  });
  await db.put("profiles", profile);
  for (const [i, metric] of [12.82, 12.65, 12.52, 12.38, 12.21].entries())
    await db.put("sessions", {
      ownerId: id,
      title: [
        "Baseline assessment",
        "Acceleration drills",
        "Sprint mechanics",
        "Speed endurance",
        "Personal best session",
      ][i],
      date: date((4 - i) * 4),
      event: "100m",
      unit: "sec",
      duration: 45 + i * 5,
      effort: 5 + (i % 3),
      metric,
      pain: 0,
      fatigue: 3 + (i % 2),
      notes: "Sample record. Replace with your actual measurements.",
      verified: false,
    });
  await db.put("achievements", {
    ownerId: id,
    title: "District athletics meet",
    date: date(20),
    level: "District",
    result: "100m · Silver medal",
    notes: "Sample achievement awaiting independent attestation.",
    verified: false,
  });
  await db.put("expenses", {
    ownerId: id,
    title: "Competition spikes",
    date: date(2),
    category: "Equipment",
    amount: 4500,
    status: "Planned",
    notes: "",
  });
}

export async function seedBenchmarks(db) {
  await ingestNationalRecordsIntoDb(db);
  if ((await db.list("benchmarks")).length > 50) return;

  const records = [
    // --- ATHLETICS: 100m Sprint Male U20 ---
    // Nashik District Records (District Tier)
    {
      id: "bm-ath-100m-nsk-1",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "district",
      country: "India",
      state: "Maharashtra",
      district: "Nashik",
      performance: { value: 11.98, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Kunal Patil",
      competition: { name: "Nashik District Junior Athletics Meet", date: "2026-02-14", location: "Nashik District Stadium" },
      source: { provider: "NDAA", name: "Nashik District Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-03-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-nsk-2",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "district",
      country: "India",
      state: "Maharashtra",
      district: "Nashik",
      performance: { value: 12.12, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Siddhesh Shinde",
      competition: { name: "Nashik District Junior Athletics Meet", date: "2026-02-14", location: "Nashik District Stadium" },
      source: { provider: "NDAA", name: "Nashik District Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-03-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-nsk-3",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "district",
      country: "India",
      state: "Maharashtra",
      district: "Nashik",
      performance: { value: 12.35, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Omkar Jadhav",
      competition: { name: "Nashik District Junior Athletics Meet", date: "2026-02-14", location: "Nashik District Stadium" },
      source: { provider: "NDAA", name: "Nashik District Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-03-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-nsk-4",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "district",
      country: "India",
      state: "Maharashtra",
      district: "Nashik",
      performance: { value: 12.45, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Pranav More",
      competition: { name: "Nashik Inter-Collegiate Sprint Trials", date: "2026-01-20", location: "Nashik" },
      source: { provider: "NDAA", name: "Nashik District Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-03-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-nsk-5",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "district",
      country: "India",
      state: "Maharashtra",
      district: "Nashik",
      performance: { value: 12.60, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Tanmay Deshmukh",
      competition: { name: "Nashik Inter-Collegiate Sprint Trials", date: "2026-01-20", location: "Nashik" },
      source: { provider: "NDAA", name: "Nashik District Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-03-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-nsk-6",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "district",
      country: "India",
      state: "Maharashtra",
      district: "Nashik",
      performance: { value: 12.75, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Aditya Gaikwad",
      competition: { name: "Nashik District Junior Athletics Meet", date: "2026-02-14", location: "Nashik" },
      source: { provider: "NDAA", name: "Nashik District Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-03-01T00:00:00Z" },
      verificationStatus: "verified",
    },

    // Maharashtra State Records (State Tier)
    {
      id: "bm-ath-100m-mah-1",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Pune",
      performance: { value: 11.62, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Rohit Kadam",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-15", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-mah-2",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Mumbai Suburban",
      performance: { value: 11.78, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Arjun Rane",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-15", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-mah-3",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Kolhapur",
      performance: { value: 11.95, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Swapnil Mane",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-15", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-mah-4",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Nagpur",
      performance: { value: 12.05, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Devendra Raut",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-15", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-mah-5",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Thane",
      performance: { value: 12.18, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Sameer Sheikh",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-15", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-mah-6",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Satara",
      performance: { value: 12.42, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Vikas Thorat",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-15", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },

    // All India National Records (National Tier)
    {
      id: "bm-ath-100m-ind-1",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Tamil Nadu",
      district: "Chennai",
      performance: { value: 10.95, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "S. K. Raman",
      competition: { name: "21st National Federation Cup U20 Athletics", date: "2025-10-18", location: "Bhopal, MP" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-ind-2",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Haryana",
      district: "Rohtak",
      performance: { value: 11.15, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Amit Malik",
      competition: { name: "21st National Federation Cup U20 Athletics", date: "2025-10-18", location: "Bhopal, MP" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-ind-3",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Kerala",
      district: "Kottayam",
      performance: { value: 11.28, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Rahul Joseph",
      competition: { name: "National Junior Athletics Championships", date: "2025-11-05", location: "Patna, Bihar" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-ind-4",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Punjab",
      district: "Jalandhar",
      performance: { value: 11.45, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Harpreet Singh",
      competition: { name: "National Junior Athletics Championships", date: "2025-11-05", location: "Patna, Bihar" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-ind-5",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Odisha",
      district: "Bhubaneswar",
      performance: { value: 11.60, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Ankit Mohanty",
      competition: { name: "National Junior Athletics Championships", date: "2025-11-05", location: "Patna, Bihar" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-100m-ind-6",
      sport: "Athletics",
      discipline: "Sprint",
      event: "100m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Delhi",
      district: "Central Delhi",
      performance: { value: 11.75, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Karan Bhasin",
      competition: { name: "21st National Federation Cup U20 Athletics", date: "2025-10-18", location: "Bhopal, MP" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },

    // --- ATHLETICS: 200m Sprint Male U20 ---
    {
      id: "bm-ath-200m-mah-1",
      sport: "Athletics",
      discipline: "Sprint",
      event: "200m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Pune",
      performance: { value: 23.40, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Rohit Kadam",
      competition: { name: "Maharashtra State Junior Athletics Championship", date: "2026-01-16", location: "Balewadi, Pune" },
      source: { provider: "MAA", name: "Maharashtra Athletics Association", url: "https://mahashreeathletics.org", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-ath-200m-ind-1",
      sport: "Athletics",
      discipline: "Sprint",
      event: "200m",
      gender: "Male",
      ageCategory: "u20",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Tamil Nadu",
      district: "Chennai",
      performance: { value: 21.80, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "S. K. Raman",
      competition: { name: "21st National Federation Cup U20 Athletics", date: "2025-10-19", location: "Bhopal, MP" },
      source: { provider: "AFI", name: "Athletics Federation of India", url: "https://indianathletics.in", retrievedAt: "2026-01-10T00:00:00Z" },
      verificationStatus: "verified",
    },

    // --- BADMINTON: Men's Singles Male U19 ---
    {
      id: "bm-bad-ms-mah-1",
      sport: "Badminton",
      discipline: "Racket",
      event: "Men's Singles",
      gender: "Male",
      ageCategory: "u19",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Pune",
      performance: { value: 540, metricType: "score", unit: "points", direction: "higher_is_better" },
      athleteName: "Chinmay Sonawane",
      competition: { name: "Maharashtra State Junior Badminton Championship", date: "2026-01-10", location: "Thane" },
      source: { provider: "MBA", name: "Maharashtra Badminton Association", url: "https://mbabadminton.com", retrievedAt: "2026-02-01T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-bad-ms-ind-1",
      sport: "Badminton",
      discipline: "Racket",
      event: "Men's Singles",
      gender: "Male",
      ageCategory: "u19",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Telangana",
      district: "Hyderabad",
      performance: { value: 850, metricType: "score", unit: "points", direction: "higher_is_better" },
      athleteName: "Ayush Shetty",
      competition: { name: "All India Junior Ranking Badminton Tournament", date: "2025-12-15", location: "Bangalore" },
      source: { provider: "BAI", name: "Badminton Association of India", url: "https://badmintonindia.org", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },

    // --- WRESTLING: Freestyle Male 65 kg (Senior) ---
    {
      id: "bm-wre-65-mah-1",
      sport: "Wrestling",
      discipline: "Freestyle",
      event: "Freestyle · 65 kg",
      gender: "Male",
      ageCategory: "senior",
      classification: "Open",
      weightCategory: "65 kg",
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Kolhapur",
      performance: { value: 92, metricType: "score", unit: "points", direction: "higher_is_better" },
      athleteName: "Mahesh Patil",
      competition: { name: "Maharashtra Rajya Kusti Samiti Senior Championship", date: "2025-11-20", location: "Kolhapur" },
      source: { provider: "MSKS", name: "Maharashtra Rajya Kusti Samiti", url: "https://maharashtrawrestling.in", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-wre-65-ind-1",
      sport: "Wrestling",
      discipline: "Freestyle",
      event: "Freestyle · 65 kg",
      gender: "Male",
      ageCategory: "senior",
      classification: "Open",
      weightCategory: "65 kg",
      level: "national",
      country: "India",
      state: "Haryana",
      district: "Jhajjar",
      performance: { value: 120, metricType: "score", unit: "points", direction: "higher_is_better" },
      athleteName: "Sujeet Kalkal",
      competition: { name: "Senior National Wrestling Championship", date: "2025-12-22", location: "Jaipur" },
      source: { provider: "WFI", name: "Wrestling Federation of India", url: "https://wrestlingfederationofindia.com", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },

    // --- WRESTLING: Freestyle Male 74 kg (Senior) ---
    {
      id: "bm-wre-74-mah-1",
      sport: "Wrestling",
      discipline: "Freestyle",
      event: "Freestyle · 74 kg",
      gender: "Male",
      ageCategory: "senior",
      classification: "Open",
      weightCategory: "74 kg",
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Sangli",
      performance: { value: 88, metricType: "score", unit: "points", direction: "higher_is_better" },
      athleteName: "Sagar Shinde",
      competition: { name: "Maharashtra Rajya Kusti Samiti Senior Championship", date: "2025-11-20", location: "Kolhapur" },
      source: { provider: "MSKS", name: "Maharashtra Rajya Kusti Samiti", url: "https://maharashtrawrestling.in", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-wre-74-ind-1",
      sport: "Wrestling",
      discipline: "Freestyle",
      event: "Freestyle · 74 kg",
      gender: "Male",
      ageCategory: "senior",
      classification: "Open",
      weightCategory: "74 kg",
      level: "national",
      country: "India",
      state: "Haryana",
      district: "Sonipat",
      performance: { value: 115, metricType: "score", unit: "points", direction: "higher_is_better" },
      athleteName: "Yash Tushir",
      competition: { name: "Senior National Wrestling Championship", date: "2025-12-22", location: "Jaipur" },
      source: { provider: "WFI", name: "Wrestling Federation of India", url: "https://wrestlingfederationofindia.com", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },

    // --- SWIMMING: 100m Freestyle Female U18 ---
    {
      id: "bm-swm-100m-mah-1",
      sport: "Swimming",
      discipline: "Aquatics",
      event: "100m Freestyle",
      gender: "Female",
      ageCategory: "u18",
      classification: "Open",
      weightCategory: null,
      level: "state",
      country: "India",
      state: "Maharashtra",
      district: "Mumbai City",
      performance: { value: 58.42, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Ananya Mehta",
      competition: { name: "Maharashtra State Junior Aquatic Championship", date: "2025-09-12", location: "Mumbai" },
      source: { provider: "GMAAA", name: "Greater Mumbai Amateur Aquatic Association", url: "https://gmaaa.org", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },
    {
      id: "bm-swm-100m-ind-1",
      sport: "Swimming",
      discipline: "Aquatics",
      event: "100m Freestyle",
      gender: "Female",
      ageCategory: "u18",
      classification: "Open",
      weightCategory: null,
      level: "national",
      country: "India",
      state: "Karnataka",
      district: "Bangalore Urban",
      performance: { value: 56.80, metricType: "time", unit: "sec", direction: "lower_is_better" },
      athleteName: "Ridhima Veerendrakumar",
      competition: { name: "National Junior Aquatic Championships", date: "2025-08-20", location: "Bhubaneswar" },
      source: { provider: "SFI", name: "Swimming Federation of India", url: "https://swimmingfederation.in", retrievedAt: "2026-01-15T00:00:00Z" },
      verificationStatus: "verified",
    },
  ];

  for (const record of records) {
    await db.put("benchmarks", record);
  }
}
