/**
 * Sprint Training Knowledge Base & Structured Exercise Library
 * Covers Athletics -> Track -> Sprint (60m, 100m, 200m, 400m).
 * Built with sports-science evidence references, coaching cues,
 * progression/regression rules, and equipment constraints.
 */

export const SPRINT_QUALITIES = [
  {
    id: "acceleration",
    name: "Acceleration Development",
    targetDistance: "0–30m",
    energySystem: "ATP-PC (alactic)",
    focus: "Horizontal force application, positive shin angles, triple extension, aggressive foot strikes under center of mass.",
    evidence: {
      citation: "Haugen et al. (2019), Alcaraz et al. (2018)",
      level: "Strong",
      notes: "Sprint acceleration is governed by the ability to generate and orient high horizontal ground reaction forces at low initial velocities.",
    },
  },
  {
    id: "maximum_velocity",
    name: "Maximum Velocity (MaxV)",
    targetDistance: "Flying 10–30m",
    energySystem: "ATP-PC (alactic)",
    focus: "Upright sprint posture, vertical stiffness, high front-side mechanics, rapid hip flexion/extension, minimal ground contact time (<0.09s).",
    evidence: {
      citation: "Morin et al. (2015), Clark & Weyand (2014)",
      level: "Strong",
      notes: "Top speed requires vertical force application in minimal contact times and high vertical leg stiffness.",
    },
  },
  {
    id: "speed_endurance",
    name: "Speed Endurance",
    targetDistance: "60–150m",
    energySystem: "Anaerobic glycolytic / Lactic",
    focus: "Mechanics retention under metabolic fatigue, relaxation, stride length consistency, deceleration mitigation.",
    evidence: {
      citation: "Haugen et al. (2014), Ae et al. (1992)",
      level: "Moderate",
      notes: "Sprinting beyond 6-7 seconds triggers rapid glycolytic flux; training emphasizes neurological coordination while buffering lactic acidosis.",
    },
  },
  {
    id: "strength",
    name: "Sprint Strength",
    targetDistance: "Gym / Field",
    energySystem: "Neuromuscular",
    focus: "Bilateral and unilateral lower-body force capacity, posterior chain (glutes/hamstrings), core rotational stiffness.",
    evidence: {
      citation: "Suchomel et al. (2016)",
      level: "Strong",
      notes: "Maximal strength serves as the foundation for rate of force development and resilience against hamstring strain injuries.",
    },
  },
  {
    id: "power_plyometrics",
    name: "Explosive Power & Plyometrics",
    targetDistance: "Track / Field",
    energySystem: "Stretch-Shortening Cycle (SSC)",
    focus: "Fast and slow stretch-shortening cycle, ankle complex stiffness, reactive strength index, horizontal and vertical displacement.",
    evidence: {
      citation: "Markovic et al. (2007)",
      level: "Strong",
      notes: "Plyometrics optimize tendon compliance and muscular pre-activation, directly translating to shortened ground contact times.",
    },
  },
  {
    id: "technique_drills",
    name: "Sprint Mechanics & Technique",
    targetDistance: "10–40m",
    energySystem: "Neuromuscular coordination",
    focus: "Dorsiflexion, knee lift, pelvic control, posture alignment, arm drive synchronization.",
    evidence: {
      citation: "Mann & Murphy (2018)",
      level: "Expert Consensus",
      notes: "Movement efficiency minimizes energy leaks and reinforces technical mastery before high-intensity loading.",
    },
  },
  {
    id: "recovery_mobility",
    name: "Mobility & Active Recovery",
    targetDistance: "Recovery Zone",
    energySystem: "Parasympathetic restoration",
    focus: "Joint mobility (hips, thoracic, ankles), soft-tissue restoration, nervous system down-regulation.",
    evidence: {
      citation: "Kellmann et al. (2018)",
      level: "Moderate",
      notes: "Planned recovery prevents overreaching and ensures adequate neurological readiness for subsequent high-velocity exposures.",
    },
  },
];

export const EXERCISE_LIBRARY = [
  // --- ACCELERATION EXERCISES ---
  {
    id: "accel-10m-falling-start",
    name: "10m Falling Starts",
    category: "Acceleration",
    trainingQuality: "acceleration",
    suitableEvents: ["60m", "100m", "200m", "400m"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Open ground / track"],
    intensityType: "maximum",
    defaultSets: 4,
    defaultReps: 1,
    defaultDistance: "10m",
    defaultRest: "90 sec",
    coachingCues: [
      "Lean from the ankles like a tree falling until your body forces the first strike.",
      "Punch the knee forward, do not cycle backwards.",
      "Drive back into the track under your hips.",
    ],
    progression: "Progress to 20m falling starts or 3-point start.",
    regression: "Wall march drills focusing on 45-degree angle.",
    contraindications: ["Acute hamstring or groin strain"],
  },
  {
    id: "accel-20m-3pt-start",
    name: "20m 3-Point Stance Acceleration",
    category: "Acceleration",
    trainingQuality: "acceleration",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Track"],
    intensityType: "maximum",
    defaultSets: 4,
    defaultReps: 1,
    defaultDistance: "20m",
    defaultRest: "2 min",
    coachingCues: [
      "Load the front leg with 70% of body weight.",
      "Violent forward arm punch on exit.",
      "Keep head neutral, eyes focused 2 meters ahead on track.",
    ],
    progression: "Block starts or resisted 20m sprints.",
    regression: "2-point athletic stance starts.",
  },
  {
    id: "accel-30m-blocks",
    name: "30m Starting Blocks Drive",
    category: "Acceleration",
    trainingQuality: "acceleration",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Starting blocks", "Track"],
    intensityType: "maximum",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "30m",
    defaultRest: "3 min",
    coachingCues: [
      "Set hips slightly above shoulders in 'Set'.",
      "Push aggressively off both pedals.",
      "Maintain drive phase transition smoothly up to 30m.",
    ],
    progression: "40m block starts with timing gates.",
    regression: "3-point stance acceleration.",
  },
  {
    id: "accel-sled-resisted",
    name: "Resisted Sled Acceleration (10–15% bodyweight)",
    category: "Acceleration",
    trainingQuality: "acceleration",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Weight sled / harness or resistance band"],
    intensityType: "maximum",
    defaultSets: 4,
    defaultReps: 1,
    defaultDistance: "15m",
    defaultRest: "2.5 min",
    coachingCues: [
      "Light load only: maintain sprint mechanics without altering stride frequency.",
      "Exaggerate horizontal projection.",
      "Push through full foot strike.",
    ],
    progression: "Contrast training: 1 resisted rep followed by 1 unresisted rep.",
    regression: "Hill sprints or falling starts.",
  },

  // --- MAXIMUM VELOCITY EXERCISES ---
  {
    id: "maxv-flying-20m",
    name: "Flying 20m Sprint (20m buildup + 20m fly)",
    category: "Maximum Velocity",
    trainingQuality: "maximum_velocity",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Track"],
    intensityType: "maximum",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "20m fly",
    defaultRest: "4 min",
    coachingCues: [
      "Build smoothly through 20m zone without straining.",
      "Hit the flying zone tall, relaxed, with rapid ground strike.",
      "Step over the opposite knee, strike directly underneath pelvis.",
      "Relax your face and jaw.",
    ],
    progression: "Flying 30m sprints with Freelap/photocells.",
    regression: "Sprint buildups over 50m with sub-maximal 90% top speed.",
  },
  {
    id: "maxv-wicket-runs",
    name: "Wicket / Mini-Hurdle Stride Runs",
    category: "Maximum Velocity",
    trainingQuality: "maximum_velocity",
    suitableEvents: ["60m", "100m", "200m", "400m"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Mini hurdles or cones"],
    intensityType: "high",
    defaultSets: 4,
    defaultReps: 1,
    defaultDistance: "30m",
    defaultRest: "2 min",
    coachingCues: [
      "Run tall over the wickets without clipping.",
      "Focus on front-side thigh elevation and stiff ankle strike.",
      "Let the spaced cones dictate rhythmic stride frequency.",
    ],
    progression: "Progressively increase wicket spacing by 5cm as speed increases.",
    regression: "Flat-ground high knee running with high tempo.",
  },

  // --- SPEED ENDURANCE EXERCISES ---
  {
    id: "speedend-80m-reps",
    name: "80m Speed Endurance Reps",
    category: "Speed Endurance",
    trainingQuality: "speed_endurance",
    suitableEvents: ["100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Track"],
    intensityType: "high (95%)",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "80m",
    defaultRest: "6 min full recovery",
    coachingCues: [
      "Accelerate cleanly for first 30m.",
      "Maintain top-end posture from 30m to 80m without tightening shoulders.",
      "Focus on rhythm and relaxation in final 20 meters.",
    ],
    progression: "100m to 120m speed endurance runs.",
    regression: "60m repeats with full recovery.",
  },
  {
    id: "speedend-120m-reps",
    name: "120m Extended Speed Endurance",
    category: "Speed Endurance",
    trainingQuality: "speed_endurance",
    suitableEvents: ["100m", "200m", "400m"],
    minimumExperienceLevel: "advanced",
    equipmentRequired: ["Track"],
    intensityType: "high (92–95%)",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "120m",
    defaultRest: "8 min full recovery",
    coachingCues: [
      "Distribute effort evenly: 95% velocity without frantic over-striding.",
      "Maintain front-side mechanics as lactic acid builds.",
    ],
    progression: "150m speed endurance reps.",
    regression: "80m speed endurance reps.",
  },

  // --- STRENGTH & POWER EXERCISES ---
  {
    id: "str-squat-patterns",
    name: "Back Squats / Box Squats",
    category: "Strength",
    trainingQuality: "strength",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Barbell / squat rack or heavy dumbells"],
    intensityType: "high (75–85% 1RM)",
    defaultSets: 4,
    defaultReps: 5,
    defaultDistance: "N/A",
    defaultRest: "2.5 min",
    coachingCues: [
      "Brace core tightly before descent.",
      "Drive up explosively through mid-foot and heel.",
      "Full hip extension at top.",
    ],
    progression: "Progressive load or paused box squats.",
    regression: "Goblet squats or bodyweight jump squats.",
  },
  {
    id: "str-nordic-hamstring",
    name: "Nordic Hamstring Curls (Injury Prevention)",
    category: "Strength",
    trainingQuality: "strength",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Partner / ankle strap"],
    intensityType: "moderate",
    defaultSets: 3,
    defaultReps: 5,
    defaultDistance: "N/A",
    defaultRest: "90 sec",
    coachingCues: [
      "Control the eccentric falling phase as slowly as possible.",
      "Keep hips locked in extension.",
      "Catch softly with hands on ground.",
    ],
    progression: "Increase eccentric time under tension (5+ seconds).",
    regression: "Swiss-ball leg curls or single-leg bridge holds.",
  },
  {
    id: "power-broad-jump",
    name: "Standing Broad Jump",
    category: "Power",
    trainingQuality: "power_plyometrics",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Open ground / sand pit / track"],
    intensityType: "maximum",
    defaultSets: 4,
    defaultReps: 2,
    defaultDistance: "Max distance",
    defaultRest: "90 sec",
    coachingCues: [
      "Hinge hips and sweep arms back dynamically.",
      "Explode horizontally forward at 45-degree trajectory.",
      "Stick the landing softly with knees tracking over toes.",
    ],
    progression: "Consecutive triple broad jump.",
    regression: "Standing vertical countermovement jumps.",
  },
  {
    id: "plyo-pogo-hops",
    name: "Ankle Pogo Hops (Reactive Stiffness)",
    category: "Power",
    trainingQuality: "power_plyometrics",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Flat ground"],
    intensityType: "high",
    defaultSets: 3,
    defaultReps: 15,
    defaultDistance: "In place",
    defaultRest: "60 sec",
    coachingCues: [
      "Keep ankles stiff and toes pulled up (dorsiflexed).",
      "Minimize knee bend; bounce off the ground like a rubber ball.",
      "Minimal contact time.",
    ],
    progression: "Single-leg pogo hops or hurdle hops.",
    regression: "Double-leg low calf jumps.",
  },

  // --- SPRINT TECHNIQUE DRILLS ---
  {
    id: "tech-a-skips",
    name: "A-Skip Drills",
    category: "Sprint Technique",
    trainingQuality: "technique_drills",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Open ground"],
    intensityType: "moderate",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "25m",
    defaultRest: "60 sec",
    coachingCues: [
      "Crisp rhythmic knee drive to hip height.",
      "Dorsiflex the ankle, toe up.",
      "Snap the foot down under the center of mass with an active pawing motion.",
    ],
    progression: "A-Runs (High knees at speed).",
    regression: "Stationary A-March against wall.",
  },
  {
    id: "tech-dribbles",
    name: "Ankle & Calf Dribbles",
    category: "Sprint Technique",
    trainingQuality: "technique_drills",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Open ground"],
    intensityType: "moderate",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "20m",
    defaultRest: "60 sec",
    coachingCues: [
      "Step over the opposite ankle/calf in a fluid cyclical motion.",
      "Keep torso tall with neutral pelvis.",
      "Maintain active ground contact.",
    ],
    progression: "Knee-height dribbles transitioning into 20m acceleration.",
    regression: "Low ankle walking marches.",
  },

  // --- MOBILITY & RECOVERY ---
  {
    id: "mob-hip-flow",
    name: "Dynamic Hip & Ankle Mobility Flow",
    category: "Mobility",
    trainingQuality: "recovery_mobility",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Mat / ground"],
    intensityType: "low",
    defaultSets: 1,
    defaultReps: 1,
    defaultDistance: "15 min",
    defaultRest: "N/A",
    coachingCues: [
      "Half-kneeling hip flexor stretch with glute squeeze.",
      "World's greatest stretch (lunge with thoracic rotation).",
      "Banded ankle joint mobilizations.",
    ],
    progression: "Loaded mobility (Jefferson curls, cossack squats).",
    regression: "Static floor stretches.",
  },
  {
    id: "rec-light-flush",
    name: "Active Recovery Flush & Foam Rolling",
    category: "Recovery",
    trainingQuality: "recovery_mobility",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Foam roller / open ground"],
    intensityType: "very low",
    defaultSets: 1,
    defaultReps: 1,
    defaultDistance: "20 min",
    defaultRest: "N/A",
    coachingCues: [
      "10 minutes light jogging or walking.",
      "Gentle foam rolling over quads, calves, and glutes (avoid direct bone).",
      "Deep diaphragmatic breathing to stimulate parasympathetic recovery.",
    ],
    progression: "Hydrotherapy or contrast showers.",
    regression: "Complete passive rest.",
  },

  // --- PLYOMETRICS ---
  {
    id: "plyo-depth-jumps",
    name: "Depth Jumps (30cm box to vertical jump)",
    category: "Plyometrics",
    trainingQuality: "power_plyometrics",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Plyo box (30cm)", "Mat / turf"],
    intensityType: "maximum",
    defaultSets: 3,
    defaultReps: 4,
    defaultDistance: "N/A",
    defaultDuration: "N/A",
    defaultRest: "2 min",
    coachingCues: [
      "Step off the box, do not jump off.",
      "Minimize ground contact time (<0.18s) upon landing.",
      "Explode vertically upward immediately upon ground strike.",
    ],
    progression: "Increase box height to 45cm or depth jump over hurdle.",
    regression: "Box jumps or snap downs.",
    contraindications: ["Patellar tendinopathy or acute ankle sprain"],
  },
  {
    id: "plyo-single-leg-bounds",
    name: "Alternate Leg Sprint Bounds",
    category: "Plyometrics",
    trainingQuality: "power_plyometrics",
    suitableEvents: ["60m", "100m", "200m"],
    minimumExperienceLevel: "intermediate",
    equipmentRequired: ["Track or turf"],
    intensityType: "maximum",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "30m",
    defaultDuration: "N/A",
    defaultRest: "2.5 min",
    coachingCues: [
      "Drive the lead knee high with active ankle dorsiflexion.",
      "Pull the foot backward beneath the center of mass upon contact.",
      "Maximize horizontal projection with upright posture.",
    ],
    progression: "Resisted bounding or speed bounds.",
    regression: "Straight-leg bounds or skipping for height.",
  },
  {
    id: "plyo-hurdle-hops",
    name: "Continuous Mini-Hurdle Pogo Hops",
    category: "Plyometrics",
    trainingQuality: "power_plyometrics",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["5-6 Mini-hurdles (15–30cm)"],
    intensityType: "high",
    defaultSets: 3,
    defaultReps: 6,
    defaultDistance: "15m",
    defaultDuration: "N/A",
    defaultRest: "90 sec",
    coachingCues: [
      "Keep ankles stiff and toes pulled up.",
      "Bounce off the balls of the feet with minimal knee bend.",
      "Maintain tall posture with arms swinging in rhythm.",
    ],
    progression: "Single-leg pogo hops over mini hurdles.",
    regression: "Double leg in-place pogo hops.",
  },

  // --- WARM-UP ---
  {
    id: "wu-dynamic-activation",
    name: "Dynamic Sprint Warm-up & Multi-Planar Mobility",
    category: "Warm-up",
    trainingQuality: "technique_drills",
    suitableEvents: ["All sports & sprints"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Open track / ground"],
    intensityType: "low",
    defaultSets: 1,
    defaultReps: 1,
    defaultDistance: "N/A",
    defaultDuration: "15 min",
    defaultRest: "N/A",
    coachingCues: [
      "Leg swings (sagittal & frontal), walking lunges with torso reach.",
      "Inchworms, high knee hugs, heel-to-glute walking stretches.",
      "Gradually increase heart rate and body temperature.",
    ],
    progression: "Include band-resisted hip flexor marches.",
    regression: "Stationary bodyweight mobility.",
  },
  {
    id: "wu-glute-activation",
    name: "Mini-Band Glute & Pelvic Activation",
    category: "Warm-up",
    trainingQuality: "strength",
    suitableEvents: ["All sports & sprints"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Mini resistance band"],
    intensityType: "moderate",
    defaultSets: 2,
    defaultReps: 12,
    defaultDistance: "N/A",
    defaultDuration: "8 min",
    defaultRest: "45 sec",
    coachingCues: [
      "Lateral band walks with athletic quarter-squat stance.",
      "Monster walks forward and backward keeping tension in band.",
      "Glute bridge holds with knees pushed outward.",
    ],
    progression: "Heavy resistance loop or single-leg glute bridges.",
    regression: "Unbanded lateral steps.",
  },
  {
    id: "wu-build-strides",
    name: "Progressive Build-up Strides (3 x 60m)",
    category: "Warm-up",
    trainingQuality: "acceleration",
    suitableEvents: ["All sprint events"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Track"],
    intensityType: "progressive (70% - 85% - 92%)",
    defaultSets: 3,
    defaultReps: 1,
    defaultDistance: "60m",
    defaultDuration: "N/A",
    defaultRest: "90 sec",
    coachingCues: [
      "Rep 1: 70% smooth acceleration, focus on tall posture.",
      "Rep 2: 85% with quick foot turnover.",
      "Rep 3: 92% simulating competitive sprint rhythm.",
    ],
    progression: "Block start exits at 95% intensity.",
    regression: "40m build-ups capped at 75%.",
  },

  // --- COOLDOWN ---
  {
    id: "cd-flush-walk",
    name: "Aerobic Walking Flush & Metabolic Clearance",
    category: "Cooldown",
    trainingQuality: "recovery_mobility",
    suitableEvents: ["All sports & sprints"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Open ground"],
    intensityType: "very low",
    defaultSets: 1,
    defaultReps: 1,
    defaultDistance: "800m",
    defaultDuration: "10 min",
    defaultRest: "N/A",
    coachingCues: [
      "Gradual deceleration from training load.",
      "Deep breathing through the nose, long exhalations.",
      "Hydrate with electrolyte fluids.",
    ],
    progression: "Light 5-minute pool flush.",
    regression: "Gentle walking with rest breaks.",
  },
  {
    id: "cd-static-stretching",
    name: "Targeted Post-Session Lower-Body Stretching",
    category: "Cooldown",
    trainingQuality: "recovery_mobility",
    suitableEvents: ["All sports & sprints"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Mat"],
    intensityType: "very low",
    defaultSets: 1,
    defaultReps: 1,
    defaultDistance: "N/A",
    defaultDuration: "10 min",
    defaultRest: "N/A",
    coachingCues: [
      "Hamstring stretch with neutral spine (30s each side).",
      "Kneeling hip flexor and quad stretch (30s each side).",
      "Calf & Achilles stretch on wall (30s each leg).",
      "Do not bounce; hold gently at first point of resistance.",
    ],
    progression: "PNF (contract-relax) stretching with a partner.",
    regression: "Seated chair stretches.",
  },
  {
    id: "cd-parasympathetic-breathing",
    name: "Parasympathetic Down-Regulation Box Breathing",
    category: "Cooldown",
    trainingQuality: "recovery_mobility",
    suitableEvents: ["All athletes"],
    minimumExperienceLevel: "beginner",
    equipmentRequired: ["Mat / quiet space"],
    intensityType: "very low",
    defaultSets: 1,
    defaultReps: 10,
    defaultDistance: "N/A",
    defaultDuration: "5 min",
    defaultRest: "N/A",
    coachingCues: [
      "Lie supine with feet elevated on a bench or wall.",
      "Inhale 4 seconds, hold 4 seconds, exhale 6 seconds, hold 2 seconds.",
      "Shift nervous system from sympathetic to parasympathetic recovery state.",
    ],
    progression: "Guided body scan meditation.",
    regression: "Simple slow diaphragmatic breathing.",
  },
];

/**
 * Helper to retrieve exercises by category or quality
 */
export function getExercisesByQuality(qualityId) {
  return EXERCISE_LIBRARY.filter((e) => e.trainingQuality === qualityId);
}

export function getExerciseById(id) {
  return EXERCISE_LIBRARY.find((e) => e.id === id) || null;
}
